sudo: required     #we need sudo priv for dokcer

services:
    - docker 

before_install:
    - docker build -t hussam/docker-react  -f Dockerfile.dev .

script:
    - docker run hussam/docker-react  npm run test -- --coverage

