sudo: required     #we need sudo priv for dokcer

services:
    - docker 

before_install:
    - docker build -t hussam/docker-react  -f Dockerfile.dev .

script:
    - docker run hussam/docker-react  npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-269437040051"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

