
version: '3'
services:
    react-app:
        build:
            context: .   #folder that contains file for our project
            dockerfile: Dockerfile.dev  #location of our docker file    
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app

